import { useState, useRef, useCallback } from "react";
import { Share2, Download, X, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { motion, AnimatePresence } from "framer-motion";

interface ShareInsightProps {
  title: string;
  value: string;
  subtitle?: string;
  accentColor?: string;
  featureName?: string;
}

export default function ShareInsight({ title, value, subtitle, accentColor, featureName = "CreatorBrain" }: ShareInsightProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const generateImage = useCallback(async () => {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d")!;
    const w = 1200, h = 630;
    canvas.width = w;
    canvas.height = h;

    // Background
    const bg = ctx.createLinearGradient(0, 0, w, h);
    bg.addColorStop(0, "#0a0a0f");
    bg.addColorStop(1, "#121218");
    ctx.fillStyle = bg;
    ctx.fillRect(0, 0, w, h);

    // Accent glow
    const glow = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, 300);
    glow.addColorStop(0, "rgba(234, 179, 8, 0.08)");
    glow.addColorStop(1, "transparent");
    ctx.fillStyle = glow;
    ctx.fillRect(0, 0, w, h);

    // Border
    ctx.strokeStyle = "rgba(234, 179, 8, 0.3)";
    ctx.lineWidth = 2;
    ctx.roundRect(24, 24, w - 48, h - 48, 24);
    ctx.stroke();

    // Title label
    ctx.font = "600 14px Inter, system-ui, sans-serif";
    ctx.fillStyle = "#eab308";
    ctx.textAlign = "center";
    ctx.fillText(title.toUpperCase(), w / 2, 120);

    // Value
    ctx.font = "800 72px Inter, system-ui, sans-serif";
    ctx.fillStyle = "#ffffff";
    ctx.fillText(value, w / 2, 300);

    // Subtitle
    if (subtitle) {
      ctx.font = "400 22px Inter, system-ui, sans-serif";
      ctx.fillStyle = "#a1a1aa";
      const lines = wrapText(ctx, subtitle, w - 200);
      lines.forEach((line, i) => {
        ctx.fillText(line, w / 2, 360 + i * 32);
      });
    }

    // Watermark
    ctx.font = "700 16px Inter, system-ui, sans-serif";
    ctx.fillStyle = "rgba(234, 179, 8, 0.6)";
    ctx.fillText(`Generated by ${featureName} ⚡`, w / 2, h - 60);

    return canvas.toDataURL("image/png");
  }, [title, value, subtitle, featureName]);

  function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
    const words = text.split(" ");
    const lines: string[] = [];
    let current = "";
    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      if (ctx.measureText(test).width > maxWidth) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines.slice(0, 3);
  }

  async function handleDownload() {
    const dataUrl = await generateImage();
    const link = document.createElement("a");
    link.download = `creatorbrain-${title.toLowerCase().replace(/\s+/g, "-")}.png`;
    link.href = dataUrl;
    link.click();
  }

  async function handleCopy() {
    try {
      const dataUrl = await generateImage();
      const blob = await (await fetch(dataUrl)).blob();
      await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: copy text
      await navigator.clipboard.writeText(`${title}: ${value}${subtitle ? ` — ${subtitle}` : ""}\n\nGenerated by CreatorBrain ⚡`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <>
      <Button
        variant="ghost"
        size="sm"
        onClick={() => setOpen(true)}
        className="gap-1.5 text-xs text-muted-foreground hover:text-foreground"
      >
        <Share2 className="h-3.5 w-3.5" />
        Share
      </Button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
            onClick={() => setOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="w-full max-w-lg rounded-2xl p-6"
              style={{ background: "hsl(var(--background-card))", border: "1px solid hsl(var(--border))" }}
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-5">
                <h3 className="text-lg font-semibold">Share This Insight</h3>
                <button onClick={() => setOpen(false)} className="text-muted-foreground hover:text-foreground">
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Preview card */}
              <div
                ref={cardRef}
                className="rounded-xl p-8 text-center mb-5"
                style={{
                  background: "linear-gradient(135deg, hsl(var(--background)) 0%, hsl(var(--background-card)) 100%)",
                  border: "1px solid hsl(var(--primary) / 0.2)"
                }}
              >
                <p className="t-label text-primary mb-3">{title}</p>
                <p className="text-4xl font-extrabold mb-2">{value}</p>
                {subtitle && <p className="text-sm text-muted-foreground">{subtitle}</p>}
                <p className="text-[10px] text-primary/50 mt-4 font-semibold">Generated by CreatorBrain ⚡</p>
              </div>

              <div className="flex gap-3">
                <Button onClick={handleDownload} className="flex-1 rounded-xl gap-2">
                  <Download className="h-4 w-4" /> Download Image
                </Button>
                <Button
                  onClick={handleCopy}
                  variant="secondary"
                  className="flex-1 rounded-xl gap-2"
                >
                  {copied ? <Check className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
                  {copied ? "Copied!" : "Copy to Clipboard"}
                </Button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
