// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpfppufxilrkoupovaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZnBwdWZ4aWxya291cG92YWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODQ2NTUsImV4cCI6MjA4ODU2MDY1NX0.zmOGnoxvTsn3-OK21jMtbpn_Qo6cPKGSXivDrRDhbbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});